server {
    listen 80;
    root /usr/share/nginx/html/wk-cb;
    index index.html;

    location ~* \.(js|css|png|jpg|gif|ico|woff2)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}