server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Archivos estáticos de /wk-cb/
    location /wk-cb/ {
        try_files $uri $uri/ /wk-cb/index.html;
    }

    # Redirigir raíz a /wk-cb/
    location = / {
        return 301 /wk-cb/;
    }
}