server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /finanzas/ {
        try_files $uri $uri/ /finanzas/index.html;
    }

    location ~* \.(js|css|woff2?|ttf|eot|svg|png|jpg|ico)$ {
        add_header Cache-Control "no-cache";
    }
}
