import { FilaEstructura } from '../models/wk.models';

export const ESTRUCTURA_WK_MENSUAL: FilaEstructura[] = [
  { nombre: 'ACTIVO CORRIENTE',           tipo: 'seccion', indent: 0 },
  { nombre: 'BANCOS',                      tipo: 'grupo',   indent: 1 },
  { nombre: 'BCP',                         tipo: 'item',    indent: 2 },
  { nombre: 'INTERBANK',                   tipo: 'item',    indent: 2 },
  { nombre: 'BBVA',                        tipo: 'item',    indent: 2 },
  { nombre: 'CAJA AREQUIPA',               tipo: 'item',    indent: 2 },
  { nombre: 'PICHINCHA',                   tipo: 'item',    indent: 2 },
  { nombre: 'BNACION',                     tipo: 'item',    indent: 2 },
  { nombre: 'PROSEGUR',                    tipo: 'grupo',   indent: 1 },
  { nombre: 'INVENTARIOS',                 tipo: 'grupo',   indent: 1 },
  { nombre: 'CHIMBOTE BEBIDAS',            tipo: 'item',    indent: 2 },
  { nombre: 'CHIMBOTE SNACKS',             tipo: 'item',    indent: 2 },
  { nombre: 'HUARAZ',                      tipo: 'item',    indent: 2 },
  { nombre: 'HUARAZ PURINA',               tipo: 'item',    indent: 2 },
  { nombre: 'PUNO',                        tipo: 'item',    indent: 2 },
  { nombre: 'TRUJILLO',                    tipo: 'item',    indent: 2 },
  { nombre: 'LIMA MONDELEZ',               tipo: 'item',    indent: 2 },
  { nombre: 'CUENTAS POR COBRAR',          tipo: 'grupo',   indent: 1 },
  { nombre: 'BACKUS',                      tipo: 'item',    indent: 2 },
  { nombre: 'A 03 - 10 DÍAS',              tipo: 'item',    indent: 2 },
  { nombre: 'A 90 DÍAS',                   tipo: 'item',    indent: 2 },
  { nombre: 'DVM',                         tipo: 'item',    indent: 2 },
  { nombre: 'VENTA EN RUTA',               tipo: 'grupo',   indent: 1 },
  { nombre: 'CRÉDITOS FISCALES',           tipo: 'grupo',   indent: 1 },
  { nombre: 'IGV',                         tipo: 'item',    indent: 2 },
  { nombre: 'RENTA',                       tipo: 'item',    indent: 2 },
  { nombre: 'TOTAL DE ACTIVO CORRIENTE',   tipo: 'total',   indent: 0 },
  { nombre: 'PASIVO CORRIENTE',            tipo: 'seccion', indent: 0 },
  { nombre: 'CTAS POR PAGAR',              tipo: 'grupo',   indent: 1 },
  { nombre: 'G&G',                         tipo: 'grupo',   indent: 1 },
  { nombre: 'SALARIOS',                    tipo: 'item',    indent: 2 },
  { nombre: 'MOVILIDADES',                 tipo: 'item',    indent: 2 },
  { nombre: 'PROVISIÓN CTS',               tipo: 'item',    indent: 2 },
  { nombre: 'PROVISIÓN GRATIFICACIÓN',     tipo: 'item',    indent: 2 },
  { nombre: 'BONO ANUAL',                  tipo: 'item',    indent: 2 },
  { nombre: 'UTILIDADES',                  tipo: 'item',    indent: 2 },
  { nombre: 'PROVEEDORES PRINCIPALES',     tipo: 'grupo',   indent: 1 },
  { nombre: 'CBC',                         tipo: 'item',    indent: 2 },
  { nombre: 'SNACKS Trux',                 tipo: 'item',    indent: 2 },
  { nombre: 'NESTLE',                      tipo: 'item',    indent: 2 },
  { nombre: 'SNACKS Chimbote',             tipo: 'item',    indent: 2 },
  { nombre: 'MONDELEZ',                    tipo: 'item',    indent: 2 },
  { nombre: 'BACKUS (Prov)',               tipo: 'item',    indent: 2 },
  { nombre: 'Facturas',                    tipo: 'subitem', indent: 3 },
  { nombre: 'Envases',                     tipo: 'subitem', indent: 3 },
  { nombre: 'PROVEEDORES SECUNDARIOS',     tipo: 'grupo',   indent: 1 },
  { nombre: 'COMODATO ENVASE EN GARANTÍA', tipo: 'grupo',   indent: 1 },
  { nombre: 'IMPUESTOS',                   tipo: 'grupo',   indent: 1 },
  { nombre: 'ITAN',                        tipo: 'item',    indent: 2 },
  { nombre: 'IGV (imp)',                   tipo: 'item',    indent: 2 },
  { nombre: 'RENTA (imp)',                 tipo: 'item',    indent: 2 },
  { nombre: 'PERCEPCIONES',               tipo: 'item',    indent: 2 },
  { nombre: 'ESSALUD',                     tipo: 'item',    indent: 2 },
  { nombre: 'AFP',                         tipo: 'item',    indent: 2 },
  { nombre: 'DETRACCIONES',               tipo: 'grupo',   indent: 1 },
  { nombre: 'OBLIGACIONES FINANCIERAS',    tipo: 'grupo',   indent: 1 },
  { nombre: 'BCP (Ob)',                    tipo: 'item',    indent: 2 },
  { nombre: 'INTERBANK (Ob)',              tipo: 'item',    indent: 2 },
  { nombre: 'PICHINCHA (Ob)',              tipo: 'item',    indent: 2 },
  { nombre: 'CONTRATO MUTUO',             tipo: 'item',    indent: 2 },
  { nombre: 'TOTAL PASIVO CORRIENTE',      tipo: 'total',   indent: 0 },
  { nombre: 'WK',                          tipo: 'wk',      indent: 0 },
  { nombre: 'PAGO A CUENTA RENTA',         tipo: 'pago',    indent: 0 },
];

export const FECHAS_DEFAULT_MENSUAL: string[] = [
  'Dic 2025', 'Ene 2026'
];